import "./globals.css";
import { Cormorant_Garamond, Pinyon_Script, Aref_Ruqaa } from "next/font/google";
import { italianno } from "./fonts/fonts";
import { Toaster } from "@/components/ui/sonner";
import { Metadata } from "next";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-serif",
});

const pinyonScript = Pinyon_Script({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-script",
});

const arefRuqaa = Aref_Ruqaa({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: "--font-arabic",
});


export const metadata: Metadata = {
  title: "Youssef && Hana",
  description: "Beautiful online wedding invitations ,Generated by Youssef Elmahallawy",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html dir="ltr" lang="en">
      <body className={`${cormorant.variable}  ${pinyonScript.variable} ${arefRuqaa.variable} ${italianno.variable}  font-sans`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
